### PR TITLE
Guillerodriguez miscfixes

### PR DESCRIPTION
**Pull request by guillerodriguez**
- Some minor changes in pagekitec client
- Add missing braces to avoid calling fflush(log_file) on ANDROID if log_file is not used.

### CODE REVIEW

**Comment by karlp** [comment]
commit 4 :+1:

**Comment by BjarniRunar** [comment]
Copying my comments from the other PR:

Hi Guillermo!

Thanks for working on this. However, I can't merge this as is:

1) By hard-coding in the DEFAULTS flag, you've broken the ability to change individual settings. I suggest adding a new flag (-D) that just sets all the flags at once to the default value.

2) Similarly, you can't just remove the HAVE_LUA and HAVE_OPENSSL defines; that breaks pagekiteco for people that have those features available. If pagekitec would import the config.h, that would be different, but in general I'm not entirely sure how we should be handling this which is why those are hard-coded in at the moment.

You are of course welcome to make any changes you like at your end, but I can't merge these into the mainline as-is.

More:

I like the intent of the -V flag, but as a user-interface it's pretty terrible. As command-line args of a tool like this are effectively an API, which others (such as yourselves) will depend upon in development of their own tools, I think we might want to put a bit more effort into making that easy to work with. We also have a very serious future-proofing problem right there: at the moment, the values of the flags are nowhere exposed outside of auto-generated and compiled code, and the compiler takes care of translating names to bitmasks. As soon as you put the bits directly into an API, I can't shuffle them around anymore without breaking tools which use -V.

**Comment by guillerodriguez** [comment]
Hi Bjarni,

1) You are right. I didn't realize how PK_WITH_DEFAULTS works; I though it merely contained default flag values. Now I see this isn't the case. I think there's not much point in this -D option as the default flag values in pagekitec already matched the values you would get when using PK_WITH_DEFAULTS.

2) Actually, pagekitec *does* import config.h already, via pkcommon.h, so no need to hardcode HAVE_LUA or HAVE_OPENSSL.

3) I see your point with -V. However without this there is no way to fine tune the logmask. Wouldn't it be better to have this as an option, even if this is documented as not "future-proof"?

Anyway I think the best is to split this into pieces and send these as separate PRs, this way you can cherry pick the bits you want.

**Comment by BjarniRunar** [comment]
Re 2) - oh! Good catch, I had somehow missed that and just trusted past-me to be doing something sensible. Seems he was just being silly.

Regarding 3), the future-proof way to handle this would be to define actual words that the user can specify on the command line, and pagekitec would convert the words to actual bitmasks using a lookup.

**Comment by guillerodriguez** [comment]
3) OK, not sure if that's worth the effort though. I'll drop it for the time being, along with the PK_WITH_DEFAULTS thing.

The other two commits are split in separate PRs:

 * #25, corresponds to commit 2 (removes hardcoded defines in pagekitec)
 * #24, corresponds to commit 4 (missing braces on Android)

**Pull request closed without merging**
